# /etc/wpa_supplicant/wpa_supplicant.conf
# debug  wpa_supplicant -c /etc/wpa_supplicant/wpa_supplicant.conf -i wlan0 &
# wpa_passphrase [ ssid ]  [ passphrase ]
country=CH 
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
        ssid="bordaile" 
        #psk="bordaile-cvlg" - paradelta
        psk=c086d06237638200423b75c16894dc5703d511c6104fa5c56b52f7cac7dfc338
}
